"""
Strategy Interface and Implementations.

This module defines how trading decisions are made based on
theoretical pricing vs. market pricing.
"""

from abc import ABC, abstractmethod
from typing import List, Dict, Any, Tuple, Optional, Union
from dataclasses import dataclass
import pandas as pd
from tqdm import tqdm
import numpy as np
from datetime import datetime
import sys
import os

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ..pricing.pricer import black_scholes_price, intrinsic_value
from ..pricing.greeks import delta, calculate_all_greeks
from ..volatility.forecasting import GARCHForecaster, MLForecaster
from ..volatility.surface import VolatilitySurface
from ..backtest.engine import Trade

@dataclass
class TradeSignal:
    """Signal generated by a strategy."""
    symbol: str
    action: str              # 'buy' or 'sell'
    quantity: int            # Number of contracts
    market_price: float
    theo_price: float
    mispricing_pct: float    # (market - theo) / theo
    
    # Option metadata
    strike: float
    expiry: datetime
    option_type: str         # 'call' or 'put'
    
    # Delta hedge info
    delta: float
    hedge_quantity: float    # Shares of stock to trade
    
    # Additional metadata for analysis
    timestamp: datetime
    underlying_price: float
    dte: float               # Days to expiry

class BaseStrategy(ABC):
    """Abstract base class for all strategies."""
    
    @abstractmethod
    def generate_signals(self, 
                        portfolio, 
                        options_snapshot: pd.DataFrame,
                        underlying_price: float,
                        current_date: datetime,
                        risk_free_rate: float) -> List[TradeSignal]:
        """
        Core logic: Compare theo vs market, generate trades.
        
        Args:
            portfolio: Current Portfolio object
            options_snapshot: DataFrame of available options for this date
            underlying_price: Current SPY price
            current_date: Current date
            risk_free_rate: Current risk-free rate
            
        Returns:
            List of TradeSignal objects
        """
        pass
    
    @abstractmethod
    def create_trade_from_signal(self, signal: TradeSignal, trade_type: str) -> Trade:
        """
        Convert a TradeSignal to a Trade object.
        
        Args:
            signal: TradeSignal to convert
            trade_type: 'option' or 'stock' (for hedge)
            
        Returns:
            Trade object ready for execution
        """
        pass

class MispricingStrategy(BaseStrategy):
    """
    Strategy that trades based on mispricing between theoretical and market prices.
    
    Logic:
        1. Calculate theoretical price for each option using vol model
        2. Compare to market price
        3. If |market - theo| / theo > threshold:
           - market > theo → SELL (overpriced)
           - market < theo → BUY (underpriced)
        4. For each option trade, generate delta-hedge stock trade
        
    Interview Tips:
        - Explain why delta-neutral: Isolates vol bet from directional exposure
        - Discuss transaction costs: Options are expensive ($0.50/contract)
        - Risk management: Max positions limit prevents over-concentration
    """
    
    def __init__(self, 
                 vol_model,
                 returns_data: Optional[pd.Series] = None,
                 threshold: float = 0.10,
                 max_positions: int = 5,
                 contracts_per_trade: int = 1):
        """
        Initialize mispricing strategy.
        
        Args:
            vol_model: Volatility forecasting model (GARCH, ML, Historical, or Surface)
            threshold: Minimum mispricing % to trade (e.g., 0.10 = 10%)
            max_positions: Maximum number of option positions to hold
            contracts_per_trade: Number of contracts per trade
        """
        self.vol_model = vol_model
        self.threshold = threshold
        self.returns_data = returns_data
        self.max_positions = max_positions
        self.contracts_per_trade = contracts_per_trade
        self.model_name = vol_model.__class__.__name__
        
    def calculate_theo_price(self, 
                            S: float, 
                            K: float, 
                            T: float, 
                            r: float, 
                            option_type: str,
                            returns_data: Optional[pd.Series] = None) -> Tuple[float, float]:
        """
        Calculate theoretical option price using the vol model.

        Args:
            S: Current underlying price
            K: Strike price
            T: Time to expiration (years)
            r: Risk-free rate
            option_type: 'call' or 'put'
            
        Returns:
            Theoretical option price

        Steps:
            1. Get volatility forecast from self.vol_model
               - Handle 4 different model types:
                 a) GARCHForecaster: Call .forecast(horizon) with DTE in days
                 b) MLForecaster: Call .forecast(returns) with historical returns
                 c) VolatilitySurface: Call .get_vol(K, S, dte, option_type)
                 d) Simple float or callable: Use directly or call with (S, K, T)
                 
            2. Calculate theoretical price using Black-Scholes
               - Use: black_scholes_price(S, K, T, r, sigma, option_type)
               
            3. Return the theoretical price
            
        Hints:
            - Use isinstance() to check model type
            - For GARCH: horizon = days to expiry (T * 365)
            - For ML: Pass self.returns_data up to current_date
            - Consider caching forecasts if same date/model called multiple times
        """
        # If at, or very near, expiration, return intrinsic value. It won't matter
        if T < 1e-6:
            return intrinsic_value(S=S,K=K,option_type=option_type)

        if isinstance(self.vol_model, VolatilitySurface):
            sigma = self.vol_model.get_vol(K, S, (T*365)) # Ensure days/years unit is proper!!!!
        
        # --------------------------------------------------------------------------------------------- IMPLEMENT OTHER VOL MODELING
        else: # Use historical volatility if no modeling class is defined
            sigma = self.vol_model


        if sigma < 0:
            print(f"Warning!! Negative vol produced: {sigma} // Check vol modeling method!")

        # Calculate theoretical price
        theo = black_scholes_price(S=S,K=K,T=T,r=r, sigma=sigma,option_type=option_type)

        return theo, sigma

    def generate_signals(self, 
                        portfolio, 
                        options_snapshot: pd.DataFrame,
                        underlying_price: float,
                        current_date: datetime,
                        risk_free_rate: float = 0.02) -> List[TradeSignal]:
        """
        Generate trading signals based on mispricing.
             
        Args:
            portfolio: Current Portfolio object
            options_snapshot: DataFrame with columns:
                - strike, expiry_date, call_put, mid_price, underlying_price, days_to_expiry
            underlying_price: Current SPY price
            current_date: Current date
            risk_free_rate: Risk-free rate
            
        Returns:
            List of TradeSignal objects (sorted by 'best' opportunities)

        """
        signals = []
        
        # Step 1: Check current positions
        num_current_positions = len(portfolio.positions)

        if num_current_positions >= self.max_positions:
            return []

        else:
            new_position_count = self.max_positions - num_current_positions

        
        # Step 2: Loop through options and find mispricings
        for _, row in tqdm(options_snapshot.iterrows()):
            # Extract option data
            symbol = row['act_symbol']
            option_K = row['strike']
            option_T = row['days_to_expiry'] / 365
            option_type = row['call_put']
            option_bid = row['bid']
            option_ask = row['ask']
            option_mid = row['mid_price']
            option_expiry=row['expiration']
            option_theo, option_sigma = self.calculate_theo_price(S=underlying_price, 
                                                    K=option_K,
                                                    T=option_T,
                                                    r=risk_free_rate,
                                                    option_type=option_type)
            # Calculate mispricing and compare to determined threshold
            mispricing_pct = (option_mid - option_theo) / option_theo

            if abs(mispricing_pct) > self.threshold:
                dec = 'sell' if option_mid > option_theo else 'buy'
                
                # Calculate delta for hedging
                option_delta = delta(S=underlying_price, 
                                     K=option_K,
                                     T=option_T,
                                     r=risk_free_rate,
                                     sigma=option_sigma,  # Does it make sense to use the calculated IV? For the Theo? Unsure...
                                     option_type=option_type)

                contract_qty = self.contracts_per_trade if dec == 'buy' else -self.contracts_per_trade

                hedge_qty = -option_delta * 100 * contract_qty

                opt_signal = TradeSignal(
                                        symbol,
                                        action=dec,
                                        quantity=contract_qty,
                                        market_price=option_mid,
                                        theo_price=option_theo,
                                        mispricing_pct=mispricing_pct,
                                        strike=option_K,
                                        expiry=option_expiry,
                                        option_type=option_type,
                                        delta=option_delta,
                                        hedge_quantity=hedge_qty,
                                        timestamp=current_date,
                                        underlying_price=underlying_price,
                                        dte=option_T)
                signals.append(opt_signal)

        # Sort by mispricing magnitude and Return top N signals
        signals.sort(key=lambda x: abs(x.mispricing_pct), reverse=True)

        return signals[:new_position_count]
    
    def create_trade_from_signal(self, signal: TradeSignal, trade_type: str) -> Trade:
        """
        Convert a TradeSignal to a Trade object for execution.
        
        This handles the conversion from strategy signal to actual trade.
        
        Args:
            signal: TradeSignal object with trade details
            trade_type: 'option' or 'stock'
                - 'option': Create option trade from signal
                - 'stock': Create delta hedge trade
                
        Returns:
            Trade object ready for portfolio.execute_trade()\
        
        Structure:
            if trade_type == 'option':
                - symbol = signal.symbol (e.g., 'SPY')
                - quantity = signal.quantity (positive for buy, negative for sell)
                  * If action='buy': quantity = +self.contracts_per_trade
                  * If action='sell': quantity = -self.contracts_per_trade
                - price = signal.market_price
                - Include option metadata: strike, expiry, option_type
                
            elif trade_type == 'stock':
                - symbol = signal.symbol (e.g., 'SPY')
                - quantity = signal.hedge_quantity (calculated from delta)
                - price = signal.underlying_price
                - No option metadata (set to None)
                
        Hints:
            - Trade dataclass from engine.py requires:
              Trade(symbol, quantity, price, trade_type, timestamp,
                    strike=None, expiry=None, option_type=None)
            - Hedge quantity is OPPOSITE of option delta exposure
              * Long call (+delta) → Short stock (negative quantity)
              * Short call (-delta) → Long stock (positive quantity)
            - Use signal.timestamp for trade timestamp

        """
        if trade_type == 'option':
            # Create option trade
            trade = Trade(
                symbol=signal.symbol,
                quantity=signal.quantity,
                price=signal.market_price,
                trade_type='option',
                timestamp=signal.timestamp,
                strike=signal.strike,
                expiry=signal.expiry,
                option_type=signal.option_type
            )
            
        elif trade_type == 'stock':
            # Create delta hedge trade
            trade = Trade(
                symbol=signal.symbol,
                quantity=signal.hedge_quantity,
                price=signal.underlying_price,
                trade_type='stock',
                timestamp=signal.timestamp,
                strike=None,
                expiry=None,
                option_type=None
            )
        else:
            raise ValueError(f"Unknown trade_type: {trade_type}")
        
        return trade


# ============================================================================
# HELPER FUNCTIONS FOR STRATEGY ANALYSIS
# ============================================================================

def create_option_key(symbol: str, strike: float, expiry: datetime, option_type: str) -> str:
    """Create unique identifier for an option."""
    return f"{symbol}_{strike:.0f}{option_type[0].upper()}_{expiry.strftime('%Y%m%d')}"



def count_option_positions(portfolio) -> int:
    """
    Count number of option positions in portfolio.
    
    Helper function for position management.
    
    Args:
        portfolio: Portfolio object from engine.py
        
    Returns:
        Number of option positions (not stock positions)
        
    TODO: IMPLEMENT THIS (EASY)
    
    Hint: Loop through portfolio.positions, count where position_type == 'option'
    """
    # TODO: YOUR CODE HERE
    return 0


def calculate_signal_quality_metrics(signals: List[TradeSignal]) -> Dict[str, float]:
    """
    Calculate metrics about signal quality for analysis.
    
    This is OPTIONAL but useful for Phase 5 analysis.
    
    Args:
        signals: List of TradeSignal objects
        
    Returns:
        Dict with metrics:
            - avg_mispricing: Average absolute mispricing
            - max_mispricing: Largest mispricing
            - avg_delta: Average absolute delta
            - num_calls: Number of call signals
            - num_puts: Number of put signals
            - num_buys: Number of buy signals
            - num_sells: Number of sell signals
    """
    if not signals:
        return {
            'avg_mispricing': 0.0,
            'max_mispricing': 0.0,
            'avg_delta': 0.0,
            'num_calls': 0,
            'num_puts': 0,
            'num_buys': 0,
            'num_sells': 0
        }
    
    # TODO: OPTIONAL - Implement for analysis
    pass
