"""
Strategy Interface and Implementations.

This module defines how trading decisions are made based on
theoretical pricing vs. market pricing.
"""

from abc import ABC, abstractmethod
from typing import List, Dict, Any, Tuple, Optional, Union
from dataclasses import dataclass
import pandas as pd
from tqdm import tqdm
import numpy as np
from datetime import datetime
import sys
import os

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pricing.pricer import black_scholes_price, intrinsic_value
from pricing.greeks import delta
from volatility.forecasting import GARCHForecaster, MLForecaster
from volatility.historical import RollingVolCalculator
from backtest.engine import Trade

@dataclass
class TradeSignal:
    """Signal generated by a strategy."""
    symbol: str
    action: str              # 'buy' or 'sell'
    quantity: int            # Number of contracts
    market_price: float
    theo_price: float
    mispricing_pct: float    # (market - theo) / theo
    
    # Option metadata
    strike: float
    expiry: datetime
    option_type: str         # 'call' or 'put'
    
    # Delta hedge info
    delta: float
    hedge_quantity: float    # Shares of stock to trade
    
    # Additional metadata for analysis
    timestamp: datetime
    underlying_price: float
    dte: float               # Days to expiry
    implied_vol: float       # Store IV for daily rebalancing

class MispricingStrategy():
    """
    Strategy that trades based on mispricing between theoretical and market prices.
    
    Logic:
        1. Calculate theoretical price for each option using vol model
        2. Compare to market price
        3. If |market - theo| / theo > threshold:
           - market > theo → SELL (overpriced)
           - market < theo → BUY (underpriced)
        4. For each option trade, generate delta-hedge stock trade
        
    Interview Tips:
        - Explain why delta-neutral: Isolates vol bet from directional exposure
        - Discuss transaction costs: Options are expensive ($0.50/contract)
        - Risk management: Max positions limit prevents over-concentration
    """
    
    def __init__(self, 
                 vol_model,
                 options_data: Optional[pd.DataFrame] = None,
                 prices_data: Optional[pd.DataFrame] = None,
                 threshold: float = 0.10,
                 exit_threshold: float = 0.10,
                 max_positions: int = 5,
                 contracts_per_trade: int = 100,
                 max_leverage: float = 1.0,
                 max_position_pct: float = 0.50,
                 max_short_exposure: float = 0.50,
                 risk_premium: float = 0.0):
        """
        Initialize mispricing strategy.
        
        Args:
            vol_model: Volatility forecasting model (GARCH, ML, Historical, or Surface)
            returns_data: Historical returns for GARCH/ML models
            options_data: Full options dataset for vol surface refitting
            prices_data: Price data for historical volatility calculator
            threshold: Minimum mispricing % to trade (e.g., 0.10 = 10%)
            exit_threshold: Mispricing % below which to exit early (e.g., 0.05 = 5%)
                           Set to 0.0 to disable early exits (hold to expiry)
            max_positions: Maximum number of option positions to hold
            contracts_per_trade: Max number of contracts per trade (reduced if capital limits hit)
            max_leverage: Maximum total capital usage / equity ratio (e.g., 3.0 = 3x)
            max_position_pct: Maximum single position capital as % of equity
            max_short_exposure: Maximum short position value as % of equity
            risk_premium: Variance risk premium multiplier (e.g., 0.15 = add 15% to vol forecast)
                         Set to 0.0 to disable. Applies to realized vol models (GARCH, Historical)
                         Typical range: 0.10-0.30. Accounts for IV > RV on average.
        """
        self.vol_model = vol_model
        self.threshold = threshold
        self.exit_threshold = exit_threshold
        self.options_data = options_data
        self.prices_data = prices_data
        self.max_positions = max_positions
        self.contracts_per_trade = contracts_per_trade
        self.max_leverage = max_leverage
        self.max_position_pct = max_position_pct
        self.max_short_exposure = max_short_exposure
        self.risk_premium = risk_premium
        self.model_name = vol_model.__class__.__name__
    
    def calculate_capital_usage(self, portfolio) -> Tuple[float, float, float]:
        """
        Calculate current capital usage, short exposure, and equity.
        
        Capital usage is the actual market value of all positions:
        - Long options: quantity * current_price * 100
        - Short options: quantity * current_price * 100 (absolute value)
        - Long stock: quantity * current_price
        - Short stock: quantity * current_price (absolute value)
        
        Args:
            portfolio: Portfolio object with current positions
            
        Returns:
            Tuple of (capital_used, short_exposure, current_equity)
        """
        capital_used = 0.0
        short_exposure = 0.0
        
        for _, pos in portfolio.positions.items():
            if pos.position_type == 'option':
                # Option value: quantity * price * 100 (multiplier)
                position_value = abs(pos.quantity) * pos.current_price * 100
                capital_used += position_value
                
                # Track short exposure separately
                if pos.quantity < 0:
                    short_exposure += position_value
            else:
                # Stock value: quantity * price
                position_value = abs(pos.quantity) * pos.current_price
                capital_used += position_value
                
                # Track short stock exposure
                if pos.quantity < 0:
                    short_exposure += position_value
        
        # Calculate current equity (cash + positions value)
        current_equity = portfolio.cash
        for _, pos in portfolio.positions.items():
            current_equity += pos.market_value()
        
        return capital_used, short_exposure, current_equity
    
    def calculate_position_size(self, 
                               portfolio, 
                               underlying_price: float,
                               strike: float,
                               option_price: float,
                               option_delta: float,
                               action: str) -> int:
        """
        Calculate the appropriate number of contracts based on risk limits.
        
        Uses actual position values:
        - Long options: premium cost
        - Short options: premium value
        - Delta hedge: stock value
        
        Args:
            portfolio: Portfolio object
            underlying_price: Current underlying price
            strike: Option strike price
            option_price: Option premium price
            option_delta: Delta of the option
            action: 'buy' or 'sell'
            
        Returns:
            Number of contracts to trade (can be 0 if limits exceeded)
        """
        capital_used, short_exposure, current_equity = self.calculate_capital_usage(portfolio)
        
        if current_equity <= 0:
            return 0

        # Calculate available capital capacity
        max_capital = current_equity * self.max_leverage
        available_capital = max(0, max_capital - capital_used)
        
        # Calculate available short exposure capacity
        max_short_capital = current_equity * self.max_short_exposure
        available_short_capacity = max(0, max_short_capital - short_exposure)
        
        # Calculate max single position capital
        max_position_capital = current_equity * self.max_position_pct
        
        # Estimate capital required per contract
        option_capital_per_contract = option_price * 100
        
        # Delta hedge capital: buying/shorting stock
        hedge_shares = abs(option_delta) * 100
        hedge_capital_per_contract = hedge_shares * underlying_price
        
        total_capital_per_contract = option_capital_per_contract + hedge_capital_per_contract
        
        # Calculate max contracts based on available capacity
        if total_capital_per_contract > 0:
            max_contracts_total = int(available_capital / total_capital_per_contract)
            max_contracts_position = int(max_position_capital / option_capital_per_contract) if option_capital_per_contract > 0 else self.contracts_per_trade
        else:
            max_contracts_total = self.contracts_per_trade
            max_contracts_position = self.contracts_per_trade
        
        # For short positions, also check short exposure limit
        if action == 'sell':
            if option_capital_per_contract > 0:
                max_contracts_short = int(available_short_capacity / option_capital_per_contract)
            else:
                max_contracts_short = self.contracts_per_trade
        else:
            max_contracts_short = self.contracts_per_trade  # No short limit for long positions
        
        # Take the minimum of all constraints
        contracts = min(
            self.contracts_per_trade,
            max_contracts_total,
            max_contracts_position,
            max_contracts_short
        )
        
        return max(0, contracts)
        
    def calculate_theo_price(self, 
                            S: float, 
                            K: float, 
                            T: float, 
                            r: float, 
                            option_type: str,
                            current_date: datetime) -> Tuple[float, float]:
        """
        Calculate theoretical option price using the vol model.

        Args:
            S: Current underlying price
            K: Strike price
            T: Time to expiration (years)
            r: Risk-free rate
            option_type: 'call' or 'put'
            
        Returns:
            Theoretical option price

        Steps:
            1. Get volatility forecast from self.vol_model
               - Handle 4 different model types:
                 a) GARCHForecaster: Call .forecast(horizon) with DTE in days
                 b) MLForecaster: Call .forecast(returns) with historical returns
                 c) VolatilitySurface: Call .get_vol(K, S, dte, option_type)
                 d) Simple float or callable: Use directly or call with (S, K, T)
                 
            2. Calculate theoretical price using Black-Scholes
               - Use: black_scholes_price(S, K, T, r, sigma, option_type)
               
            3. Return the theoretical price
            
        Hints:
            - Use isinstance() to check model type
            - For GARCH: horizon = days to expiry (T * 365)
            - For ML: Pass self.returns_data up to current_date
            - Consider caching forecasts if same date/model called multiple times
        """
        # If at, or very near, expiration, return intrinsic value. It won't matter
        if T < 1e-6:
            return intrinsic_value(S=S,K=K,option_type=option_type), 0.0

        elif isinstance(self.vol_model, GARCHForecaster):
            sigma = self.vol_model.forecast(horizon = T*365)

        elif isinstance(self.vol_model, RollingVolCalculator):
            # Get current volatility estimate from historical calculator
            sigma = self.vol_model.get_current_vol(self.prices_data, current_date)
            if sigma is None:
                # Not enough data yet, use a default
                sigma = 0.11
        
        # --------------------------------------------------------------------------------------------- IMPLEMENT OTHER VOL MODELING (GARCH, ML)
        else: # Use scalar volatility if provided
            sigma = self.vol_model


        if sigma < 0:
            print(f"Warning!! Negative vol produced: {sigma} // Check vol modeling method!")

        # Apply variance risk premium adjustment
        # This accounts for IV > RV on average - market prices in a premium for vol protection
        if self.risk_premium > 0:
            sigma = sigma * (1 + self.risk_premium)

        # Calculate theoretical price
        theo = black_scholes_price(S=S,K=K,T=T,r=r, sigma=sigma,option_type=option_type)

        return theo, sigma
    
    def _vectorized_get_volatilities(self, df: pd.DataFrame, current_date: datetime) -> np.ndarray:
        """
        Vectorized volatility calculation for all options in dataframe.
        
        Args:
            df: DataFrame with columns 'strike', 'T' (time to expiry in years), 'days_to_expiry', 'call_put'
            underlying_price: Current underlying price
            current_date: Current date
            
        Returns:
            Array of volatilities for each option (with risk premium applied)
        """    
        if isinstance(self.vol_model, GARCHForecaster):
            # GARCH forecast is the same for all options at a given time
            if self.vol_model.is_fitted:
                single_sigma = self.vol_model.forecast(horizon=30)  # 30-day forecast
                
                # First few days of GARCH will be extremely low, model improves over time!
                if single_sigma < 0.08:                
                    print(f"Warning! Modeled volatility {single_sigma} is too low, GARCH not fitted yet, using fallback!.")
                    # Floor at 8% (SPY rarely goes below this, even in low-vol regimes)
                    single_sigma = max(single_sigma, 0.08)
                    
            sigmas = np.full(len(df), single_sigma)
        
        elif isinstance(self.vol_model, RollingVolCalculator):
            # Historical vol is the same for all options at a given time
            single_sigma = self.vol_model.get_current_vol(self.prices_data, current_date)
            if single_sigma is None:
                single_sigma = 0.11
            sigmas = np.full(len(df), single_sigma)
        
        else:
            # Scalar volatility model - broadcast to all options
            sigmas = np.full(len(df), float(self.vol_model))
        
        # Apply variance risk premium adjustment
        # This accounts for IV > RV on average - market prices in a premium for vol protection
        if self.risk_premium > 0:
            sigmas = sigmas * (1 + self.risk_premium)
        
        return sigmas

    def update_vol_model(self, current_date: datetime) -> None:
        """
        Update vol model with data available up to current_date.
        
        For VolatilitySurface: Refit surface weekly
        For GARCH/ML: Could refit with expanding window.
        For Historical vol: No need to update, calculated when needed
        
        Args:
            current_date: Current date in backtest
        """
        if isinstance(self.vol_model, GARCHForecaster):
            if self.prices_data['date'].dtype == 'object':
                self.prices_data['date'] = pd.to_datetime(self.prices_data['date'])

            # Filter to only historical price data
            historical_prices = self.prices_data[self.prices_data['date'] < current_date]

            # Fit GARCH forecaster on available data
            ret_series = historical_prices['log_ret'].dropna()
            self.vol_model.fit(ret_series)

    def check_early_exits(self,
                         portfolio,
                         options_snapshot: pd.DataFrame,
                         underlying_price: float,
                         current_date: datetime,
                         risk_free_rate: float = 0.02) -> List[Trade]:
        """
        Check if any positions should be closed early due to mispricing convergence.
        
        Exit when the option reaches fair value (mispricing < exit_threshold).
        This allows the strategy to realize P&L early and redeploy capital.
        
        Args:
            portfolio: Current Portfolio object with positions
            options_snapshot: DataFrame with current day's option prices
            underlying_price: Current SPY price
            current_date: Current date
            risk_free_rate: Risk-free rate
            
        Returns:
            List of Trade objects to close positions (both option and hedge)
        """
        closing_trades = []
        
        # Early exit disabled if threshold is 0
        if self.exit_threshold <= 0:
            return []
        
        # Loop through all option positions
        for pos_key, pos in list(portfolio.positions.items()):
            if pos.position_type != 'option':
                continue
            
            # Find current market price for this option
            option_match = options_snapshot[
                (options_snapshot['strike'] == pos.strike) &
                (options_snapshot['expiration'] == pos.expiry) &
                (options_snapshot['call_put'] == pos.option_type)
            ]
            
            # Skip if option not found in today's market data
            if len(option_match) == 0:
                continue
            
            market_price = option_match.iloc[0]['mid_price']
            
            # Calculate time to expiry
            T = max(0, (pos.expiry - current_date).days / 365.0)
            
            # Skip very near expiry options (let them expire naturally) ---------------------------------------------------------------------------
            if T < 0.01:  # Less than ~4 days
                continue
            
            # Calculate current theoretical price
            theo_price, sigma = self.calculate_theo_price(
                S=underlying_price,
                K=pos.strike,
                T=T,
                r=risk_free_rate,
                option_type=pos.option_type,
                current_date=current_date
            )
            
            # Calculate current mispricing
            if theo_price > 0:
                current_mispricing = abs((market_price - theo_price) / theo_price)
            else:
                print("Warning! Negative theoretical calculated, check pipeline!")
                continue 
            
            # Check if mispricing has converged to fair value
            if current_mispricing < self.exit_threshold:
                # Calculate delta for hedge unwinding
                opt_delta = delta(underlying_price, pos.strike, T, risk_free_rate, sigma, pos.option_type)
                
                # Create closing trade for option (opposite of current position)
                closing_qty = -pos.quantity  # Negative to close
                
                option_close_trade = Trade(
                    symbol=pos.symbol,
                    quantity=closing_qty,
                    price=market_price,
                    trade_type='option',
                    timestamp=current_date,
                    strike=pos.strike,
                    expiry=pos.expiry,
                    option_type=pos.option_type,
                    implied_vol=sigma,
                    delta=opt_delta
                )
                closing_trades.append(option_close_trade)
                
                # Create closing trade for delta hedge
                hedge_unwind_qty = opt_delta * 100 * pos.quantity
                
                hedge_close_trade = Trade(
                    symbol=pos.symbol,
                    quantity=hedge_unwind_qty,
                    price=underlying_price,
                    trade_type='stock',
                    timestamp=current_date,
                    strike=None,
                    expiry=None,
                    option_type=None
                )
                closing_trades.append(hedge_close_trade)
        
        return closing_trades

    def generate_signals(self, 
                        portfolio, 
                        options_snapshot: pd.DataFrame,
                        underlying_price: float,
                        current_date: datetime,
                        risk_free_rate: float = 0.02) -> List[TradeSignal]:
        """
        Generate trading signals based on mispricing.
             
        Args:
            portfolio: Current Portfolio object
            options_snapshot: DataFrame with columns:
                - strike, expiry_date, call_put, mid_price, underlying_price, days_to_expiry
            underlying_price: Current SPY price
            current_date: Current date
            risk_free_rate: Risk-free rate
            
        Returns:
            List of TradeSignal objects (sorted by 'best' opportunities)

        """
        signals = []
        
        # Step 1: Check current positions
        num_current_positions = len(portfolio.positions)

        if num_current_positions >= self.max_positions:
            return []

        else:
            new_position_count = self.max_positions - num_current_positions

        
        # Step 2: Vectorized calculation of mispricings
        if len(options_snapshot) == 0:
            return []
        
        # Create a copy to avoid modifying original
        df = options_snapshot.copy()
        
        # Calculate time to expiry in years (vectorized)
        df['T'] = df['days_to_expiry'] / 365
        
        # Vectorized volatility calculation
        df['sigma'] = self._vectorized_get_volatilities(df, current_date)
        
        # Handle near-expiration cases (vectorized)
        near_expiry_mask = df['T'] < 1e-6
        
        # Vectorized theoretical price calculation
        # For near-expiry: use intrinsic value
        # For normal cases: use Black-Scholes (vectorized via numpy arrays)
        df['theo_price'] = np.where(
            near_expiry_mask,
            # Intrinsic value for near expiry (vectorized)
            np.where(
                df['call_put'] == 'call',
                np.maximum(underlying_price - df['strike'], 0),
                np.maximum(df['strike'] - underlying_price, 0)
            ),
            # Black-Scholes for normal cases
            # Note: BS function uses numpy internally, so array inputs work efficiently
            np.array([
                black_scholes_price(underlying_price, K, T, risk_free_rate, sig, opt_type)
                for K, T, sig, opt_type in zip(
                    df['strike'].values,
                    df['T'].values,
                    df['sigma'].values,
                    df['call_put'].values
                )
            ])
        )
        
        # Calculate mispricing percentage (vectorized)
        df['mispricing_pct'] = (df['mid_price'] - df['theo_price']) / df['theo_price']
        
        # Filter for mispricings above threshold (vectorized)
        df_mispriced = df[df['mispricing_pct'].abs() > self.threshold].copy()
        

        # In strategy.py, add filter before calculating deltas
        df_mispriced = df_mispriced[
            (df_mispriced['strike'] / underlying_price).between(0.95, 1.05)
        ]


        if len(df_mispriced) == 0:
            return []
        
        # Determine action (vectorized)
        df_mispriced['action'] = np.where(df_mispriced['mispricing_pct'] > 0, 'sell', 'buy')
        
        # Calculate deltas (vectorized delta calculation)
        df_mispriced['delta'] = np.array([
            delta(underlying_price, K, T, risk_free_rate, sig, opt_type)
            for K, T, sig, opt_type in zip(
                df_mispriced['strike'].values,
                df_mispriced['T'].values,
                df_mispriced['sigma'].values,
                df_mispriced['call_put'].values
            )
        ])
        
        # Sort by mispricing magnitude before position sizing
        # This ensures best opportunities get capital first
        df_mispriced = df_mispriced.sort_values('mispricing_pct', key=abs, ascending=False)
        
        # Track running capital usage as we generate signals
        # This prevents over-allocation when multiple signals are generated in one batch
        capital_used, short_exposure, current_equity = self.calculate_capital_usage(portfolio)
        running_capital_used = capital_used
        running_short_exposure = short_exposure
        
        # Create TradeSignal objects with dynamic position sizing
        for _, row in df_mispriced.iterrows():
            opt_delta = row['delta']
            option_price = row['mid_price']
            action = row['action']
            strike = row['strike']
            
            # Calculate capital required for this trade
            option_capital = option_price * 100
            
            # Hedge capital (full value)
            hedge_shares = abs(opt_delta) * 100
            hedge_capital = hedge_shares * underlying_price
            
            capital_per_contract = option_capital + hedge_capital
            
            # Check if we have capacity for at least 1 contract
            max_capital = current_equity * self.max_leverage
            available_capital = max(0, max_capital - running_capital_used)
            max_position_capital = current_equity * self.max_position_pct
            
            # Check short exposure capacity
            max_short_capital = current_equity * self.max_short_exposure
            available_short_capacity = max(0, max_short_capital - running_short_exposure)
            
            if capital_per_contract > 0:
                max_contracts_total = int(available_capital / capital_per_contract)
                max_contracts_position = int(max_position_capital / option_capital) if option_capital > 0 else self.contracts_per_trade
            else:
                max_contracts_total = self.contracts_per_trade
                max_contracts_position = self.contracts_per_trade
            
            # For short positions, check short exposure limit
            if action == 'sell':
                if option_capital > 0:
                    max_contracts_short = int(available_short_capacity / option_capital)
                else:
                    max_contracts_short = self.contracts_per_trade
            else:
                max_contracts_short = self.contracts_per_trade
            
            contracts = min(self.contracts_per_trade, max_contracts_total, max_contracts_position, max_contracts_short)
            
            # Skip if we can't take any contracts due to capital limits
            if contracts <= 0:
                continue
            
            # Update running capital usage for next iteration
            running_capital_used += contracts * capital_per_contract
            
            # Update running short exposure for short positions
            if action == 'sell':
                running_short_exposure += contracts * option_capital
            
            # Apply direction (buy = positive, sell = negative)
            contract_qty = contracts if action == 'buy' else -contracts
            hedge_qty = -opt_delta * 100 * contract_qty
            
            opt_signal = TradeSignal(
                symbol=row['act_symbol'],
                action=action,
                quantity=contract_qty,
                market_price=option_price,
                theo_price=row['theo_price'],
                mispricing_pct=row['mispricing_pct'],
                strike=strike,
                expiry=row['expiration'],
                option_type=row['call_put'],
                delta=opt_delta,
                hedge_quantity=hedge_qty,
                timestamp=current_date,
                underlying_price=underlying_price,
                dte=row['T'],
                implied_vol=row['sigma']
            )
            signals.append(opt_signal)
            
            # Stop if we've reached max new positions
            if len(signals) >= new_position_count:
                break

        return signals
    
    def create_trade_from_signal(self, signal: TradeSignal, trade_type: str) -> Trade:
        """
        Convert a TradeSignal to a Trade object for execution.
        
        This handles the conversion from strategy signal to actual trade.
        
        Args:
            signal: TradeSignal object with trade details
            trade_type: 'option' or 'stock'
                - 'option': Create option trade from signal
                - 'stock': Create delta hedge trade
                
        Returns:
            Trade object ready for portfolio.execute_trade()
        """

        if trade_type == 'option':
            # Create option trade
            trade = Trade(
                symbol=signal.symbol,
                quantity=signal.quantity,
                price=signal.market_price,
                trade_type='option',
                timestamp=signal.timestamp,
                strike=signal.strike,
                expiry=signal.expiry,
                option_type=signal.option_type,
                implied_vol=signal.implied_vol,
                delta=signal.delta
            )
            
        elif trade_type == 'stock':
            # Create delta hedge trade
            trade = Trade(
                symbol=signal.symbol,
                quantity=signal.hedge_quantity,
                price=signal.underlying_price,
                trade_type='stock',
                timestamp=signal.timestamp,
                strike=None,
                expiry=None,
                option_type=None
            )
        
        return trade


# ============================================================================
# HELPER FUNCTIONS FOR STRATEGY ANALYSIS
# ============================================================================

def create_option_key(symbol: str, strike: float, expiry: datetime, option_type: str) -> str:
    """Create unique identifier for an option."""
    return f"{symbol}_{strike:.0f}{option_type[0].upper()}_{expiry.strftime('%Y%m%d')}"